#Message representing commanding a motor to a specific position
#units are device dependant, normally in encoder ticks
#velocity is in ticks per second

#goal definition
int32 position
float32 max_velocity
---
#result definition
int32 final_position
---
#feedback
device_driver_base/MotorFeedback feedback
